import "../../globals.css";
import React, {ReactNode} from "react";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/lib/auth";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode;
}

export default async function RootLayout({children}: RootLayoutProps) {
    const session = await auth()
    return (
        <html lang="en">
            <body>
            <SessionProvider session={session}>
                {children}
            </SessionProvider>
            </body>
        </html>
    );
}
